[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.216"
serde_json = "1.0.134"
rand = "0.9.0"
rayon = "1.10.0"
rand_distr = "0.5"
weighted_rand = "0.4.2"
csv = "1.3.1"
chrono = "0.4.40"